apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-cron-job
#  Cron job spec
spec:
#  * minute(0 - 59) * hour(0 - 23) * day of month (1 - 31) * month (1 - 12) * day of week (0 - 6)
  schedule: "*/1 * * * *"
  jobTemplate:
#    Job template spec
    spec:
      #  To set number of pods a job can use
      completions: 3
      #  Creates 3 pods in parallel, if any of the pods fail, then it smartly creates those pods only.
      parallelism: 3
      template:
#        Pod spec
        spec:
          containers:
            - name: reporting-tool
              image: reporting-tool

          restartPolicy: Never
