apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
#  To set number of pods a job can use
  completions: 3
#  Creates 3 pods in parallel, if any of the pods fail, then it smartly creates those pods only.
  parallelism: 3
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr','3','+','2']
      restartPolicy: Never