apiVersion: v1
kind: Pod
metadata:
  name: web-pod
#   Run at pod level, will be overwritten by container securityContext
  securityContext:
    runAsUser: 1000
    capabilities:
      add: [ "MAC_ADMIN" ]
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "3600"]
#   Run at container level
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]