apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
#  To use a storage class
  storageClassName: google-storage
  resources:
    requests:
      storage: 500Mi