apiVersion: v1
kind: Config
current-context: dev-user@Google
clusters:
  - name: my-kube-playground
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
#      certificate-authority-data: <encoded_certificate_password>
      server: https://my-kube-playground:6443
  - name: development
  - name: production
  - name: google
contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
      namespace: finance
  - name: dev-user@google
  - name: prod-user@production
users:
  - name: my-kube-admin
    user:
      client-certificate: /etc/kubernetes/pki/users/admin.crt
      client-key: /etc/kubernetes/pki/users/admin.key
  - name: admin
  - name: dev-user
  - name: prod-user